### PR TITLE
Fix readme typos

### PR DESCRIPTION
**Pull request by vidbina**
Just a few minor tweaks :wink:

### CODE REVIEW

**Comment by dmick** [comment]
Please accept this PR

**Comment by eosrei** [comment]
Thank you! @vidbina 

Not to step on any toes, but I can merge this so...

**Comment by vidbina** [comment]
Ha :grin: cool. Had totally forgotten about this. I'm sure this course is due for an all-around refresh since k8s, [currently at v1.8.6](https://github.com/kubernetes/kubernetes/releases/tag/v1.8.6), happens to be 6 minors ahead of v1.2.2 which is the version mentioned in the README. I vaguely recall little API and toolset changes which should probably be reflected in this course. At the very least it would help to ensure that the course is still valid for v1.8.6 :wink:

**Comment by eosrei** [comment]
It actually works as-is right now, but could probably still use a refresh. I have no idea about the Content team's roadmap though. I run our infrastructure. :laughing:

**Pull request merged**
